" Add numbers to each line on the left-hand side.
set number"

set ruler

" Turn syntax highlighting on.
syntax on

" While searching though a file incrementally highlight matching characters as you type.
set incsearch

set hlsearch
set hls

" Ignore capital letters during search.
set ignorecase

" Override the ignorecase option if searching for capital letters.
" This will allow you to search specifically for capital letters.
set smartcase

set showmode
set list
set listchars=tab:>.,trail:.

" Set shift width to 4 spaces.
set shiftwidth=4

" Set tab width to 4 columns.
set tabstop=4

" Use space characters instead of tabs.
set expandtab

" Do not save backup files.
set nobackup



set splitbelow
set splitright

set autoindent

" Enable folding
set foldmethod=indent
" set foldlevel=99
"
set laststatus=2
set colorcolumn=81
set mouse=r


" Highlight cursor line underneath the cursor horizontally.
color desert
set cursorline
" hi CursorLine term=bold cterm=bold guibg=Grey40 guifg=white ctermfg=white
" hi CursorLine term=bold cterm=bold guibg=Grey40 guifg=white guifg=Yellow
hi CursorLine term=bold cterm=bold ctermbg=Black guibg=Grey40
hi Search term=bold cterm=bold ctermfg=yellow ctermbg=black


" hi CursorLine term=bold cterm=bold guibg=Grey40 guifg=Yellow



" Highlight cursor line underneath the cursor vertically.
" set cursorcolumn

" Set the commands to save in history default number is 20.
set history=1000

" Enable auto completion menu after pressing TAB.
set wildmenu

" Make wildmenu behave like similar to Bash completion.
set wildmode=list:longest

" There are certain files that we would never want to edit with Vim.
" Wildmenu will ignore files with these extensions.
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx
set mouse=r
set expandtab
set tabstop=4
set autoindent
set showcmd
set ignorecase

syntax on
set mouse=r


function CreateTags()
    exec ':!ctags -R -f ./tags'
endfunction
nmap <silent> <F6> :call CreateTags() <CR> <CR>


